### ISSUE TITLE
Run tagger to collect tags for OSIO example stacks

### ISSUE THREAD

**Issue by SaketJNU** [fabric8-analytics/fabric8-analytics-tagger#26]
OSIO start-up example has five stacks with 13 packages belonging to *springboot* and *vert.x* and *README* file is available on S3. Run tagger to collect tags for these 13 packages. It requires:

- [ ] Check whether S3 bucket has required README files.
- [ ] run tagger to collect tags.
- [ ] update the S3 buckets with collected tags.

**Comment by fridex** [comment]
I think we can close this with respect to work being tracked in https://github.com/openshiftio/openshift.io/issues/623
